/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id:
    'eu-central-1:83fbac35-601c-4b54-a9ee-28c983ab35d5',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_HfLwUzJ0x',
  aws_user_pools_web_client_id: '6dfl26ur7la565rc343be22hrp',
  oauth: {
    domain: 'newsaggregator-dev.auth.eu-central-1.amazoncognito.com',
    scope: ['email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn:
      'http://localhost:3000/,myapp://,https://main.d29hoxfyo0vdci.amplifyapp.com/',
    redirectSignOut:
      'http://localhost:3000/,myapp://,https://main.d29hoxfyo0vdci.amplifyapp.com/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS',
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: ['GOOGLE'],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_appsync_graphqlEndpoint:
    'https://4yimvn6ugjd25jbcjx42y7iyli.appsync-api.eu-central-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-central-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket:
    'newsaggregator8688a98338a64a7da7d92178eafd61a6123111-dev',
  aws_user_files_s3_bucket_region: 'eu-central-1',
};

export default awsmobile;
